Merged PR: Tileset export and User Data
alpine-alpaca/asefile pull request #9
Opened 2021-08-03 23:02 UTC by B-Reif

This PR addresses some merge conflicts with the other two PRs I have opened. It also includes a fix for an edge case when tilemap cels overflow the image bounds.

2021-08-08 22:31 UTC, alpine-alpaca requested changes
That's one big PR. Took me 1h to review.

It's looking good though. And looks to be close to feature complete.

2021-08-08 22:31 UTC, alpine-alpaca commented on src/file.rs
> +    pub fn slices(&self) -> &Vec<Slice> {
That should return a `&[Slice]` not a borrow of a vector.

2021-08-08 22:31 UTC, alpine-alpaca commented on src/file.rs
> +fn tile_slice<'a, T>(pixels: &'a [T], tile_size: &TileSize, tile_id: &TileId) -> &'a [T] {
A comment explaining the intent of this function would be nice. It's not that obvious from the name & type.

2021-08-08 22:35 UTC, alpine-alpaca commented
Once this is merged I'll make a proper 0.3 release.

Hopefully, that should help with your other package.

2021-08-12 22:22 UTC, alpine-alpaca commented
Actually, hold on making any changes. I'm doing the cleanups myself in branch `pr-9`.

2021-08-13 21:59 UTC, B-Reif commented
Thanks for all your help on these features, I really appreciate it!

2021-08-15 14:36 UTC, merged